version: '3.8'

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11435:11434"  # change this line
    volumes:
      - .ollama:/root/.ollama  # optional: to persist models
    restart: always

  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    restart: always
